apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-manifests.yaml

# Patch microservices to include the OpenTelemetry Endpoint pointing to our collector
patches:
  # 1. Services with 'server' container
  - target:
      kind: Deployment
      labelSelector: "app in (adservice, cartservice, checkoutservice, currencyservice, emailservice, paymentservice, productcatalogservice, recommendationservice, shippingservice)"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all-boutique-servers
      spec:
        template:
          spec:
            containers:
              - name: server
                env:
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
                  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"

  # 2. Services with 'main' container
  - target:
      kind: Deployment
      name: loadgenerator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: loadgenerator
      spec:
        template:
          spec:
            containers:
              - name: main
                env:
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
                  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"

  # 3. Services with 'redis' container
  - target:
      kind: Deployment
      name: redis-cart
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis-cart
      spec:
        template:
          spec:
            containers:
              - name: redis
                env:
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
                  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"

  # 4. Resolve K3s LoadBalancer port collision
  - target:
      kind: Service
      name: frontend-external
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend-external
      spec:
        type: ClusterIP

  # 5. Remove redundant Deployment (Argo Rollout takes over in Terraform)
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
