apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-manifests.yaml

# Patch all deployments to include the OpenTelemetry Endpoint pointing to our collector
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: server
                env:
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
                  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
              - name: frontend
                env:
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
                  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                    value: "http://otel-collector-opentelemetry-collector.observability:4317"
    target:
      kind: Deployment
